lengow_test/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

from django.contrib import admin

urlpatterns = [
    url(r'^orders/', include('orders.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework'))

]

orders/urls.py
from django.conf.urls import url

from . import views

app_name = 'orders'
urlpatterns = [
    url(r'^$', views.listOrders, name='list'),
    url(r'^lunch', views.lunch, name='lunch'),
    url(r'^trun', views.truncate, name='truncate'),
    url(r'^search', views.search, name='search'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

orders/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.db import models


class MarketPlace(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name


class Orders(models.Model):
    marketplace = models.ForeignKey(MarketPlace, on_delete=models.CASCADE)
    payment_date = models.DateField(default=datetime.now, blank=True)
    order_amount = models.FloatField(default=0)
    order_id = models.CharField(max_length=255)
    order_currency = models.CharField(max_length=20)

    def __str__(self):
        return self.order_id


class Products(models.Model):
    title = models.CharField(max_length=255)
    url_image = models.TextField()
    price_unit = models.FloatField(default=0)
    quantity = models.IntegerField(default=0)
    order = models.ForeignKey(Orders, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

orders/views.py
import xml.dom.minidom

try:
    from urllib.request import urlopen
except ImportError:
    from urllib2 import urlopen
    
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
from django.views import generic

from orders.models import Orders, Products, MarketPlace


def lunch(request):
    orders_xml = urlopen('http://test.lengow.io/orders-test.xml')
    DOMTree = xml.dom.minidom.parse(orders_xml)
    collection = DOMTree.documentElement
    # Get all Orders
    orders = collection.getElementsByTagName("order")
    orderByOrder(orders)
    return HttpResponseRedirect(reverse('orders:list'))


def orderByOrder(orders):
    for order in orders:

        marketplace = getMarketplace(order)
        order_id = getData(order, 'order_id')
        payment_date = getData(order, 'payment_date')
        if payment_date == False:
            payment_date = timezone.now()
        order_amount = getData(order, 'order_amount')
        order_currency = getData(order, 'order_currency')

        save_order = Orders(order_id=order_id, payment_date=payment_date,
                            order_amount=order_amount, order_currency=order_currency, marketplace=marketplace)
        save_order.save()

        # # Get all products in order
        products = order.getElementsByTagName("product")
        for product in products:
            title = getData(product, 'title')
            url_image = getData(product, 'url_image')
            price_unit = getData(product, 'price_unit')
            quantity = getData(product, 'quantity')

            save_product = Products(
                title=title,
                url_image=url_image,
                price_unit=price_unit,
                quantity=quantity,
                order=save_order
            )

            save_product.save()


def search(request):
    all_marketplace = MarketPlace.objects.all()
    marketplace = request.GET.get('marketplace')
    date = request.GET.get('date')
    devise = request.GET.get('devise')
    amount = request.GET.get('amount')
    if marketplace == "all":
        all_orders = Orders.objects.all()
    else:
        all_orders = Orders.objects.filter(marketplace__name=marketplace)

    if date:
        all_orders = all_orders.filter(payment_date=date)
    if devise:
        all_orders = all_orders.filter(order_currency=devise)
    if amount:
        all_orders = all_orders.filter(order_amount__gte=amount)
    return render(request, 'orders/search.html', {'all_orders': all_orders, 'all_marketplace': all_marketplace})


def getMarketplace(order):
    marketplace = order.getElementsByTagName("marketplace")[0]
    marketplace_data = marketplace.childNodes[0].data
    marketplace = MarketPlace.objects.filter(name=marketplace_data)
    if not marketplace:
        m = MarketPlace(name=marketplace_data)
        m.save()
        return m
    else:
        return marketplace[0]


def getData(order, tag_name):
    a = order.getElementsByTagName(tag_name)[0]
    if a.firstChild:
        return a.firstChild.data
    else:
        return False


def listOrders(request):
    all_orders = Orders.objects.order_by('-payment_date')[:25]
    all_marketplace = MarketPlace.objects.all()

    return render(request, 'orders/list_orders.html', {'all_orders': all_orders, 'all_marketplace': all_marketplace})


class DetailView(generic.DetailView):
    model = Orders
    template_name = 'orders/detail.html'


def truncate(request):
    Orders.objects.all().delete()
    Products.objects.all().delete()
    MarketPlace.objects.all().delete()

    return HttpResponseRedirect(reverse('orders:list'))

orders/templates/global.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Test Lengow{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'orders/css/bootstrap.min.css' %}"/>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/orders">Test Lengow</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/orders/trun">Reset DB</a></li>
              <li><a href="/orders/lunch">Lunch save Orders</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<section class="container" style="margin-top: 60px;">
    {% block content %} {% endblock %}
</section>

<script src="{% static 'orders/js/jquery.min.js' %}"></script>
<script src="{% static 'orders/js/bootstrap.min.js' %}"></script>
</body>
</html>

orders/templates/orders/detail.html
{% extends 'global.html' %}
{% block title %}detail Order n° {{ orders.order_id }}{% endblock %}
{% block content %}
    <section>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    <h1>Order n° {{ orders.order_id }}</h1>
                </div>
            </div>
            <div class="panel-body text-center">
                <div class="market">{{ orders.marketplace }}</div>
                <div class="date">{{ orders.payment_date|date:'d/m/Y' }}</div>
                <div class="amount">{{ orders.order_amount }} {{ orders.order_currency }};</div>
                <div class="products">
                    {% for product in orders.products_set.all %}
                        <div class="product col-md-6">
                            <p>{{ product.quantity }} - {{ product.title }}
                                ({{ product.price_unit }} {{ orders.order_currency }} unit)</p>
                        </div>
                        <div class="col-md-6">
                            <img width="50%" src="{{ product.url_image }}" alt="IMG of {{ product.tittle }}">
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/form.html
<article id="seach" style="margin-bottom: 20px;">
    <form action="/orders/search" id="form_search">
        <div class="col-md-2">
            <select name="marketplace" id="marketplace" class="form-control">
                <option value="all">All Marketplace</option>
                {% for marketplace in all_marketplace %}
                    <option
                            {% if marketplace.name == request.GET.marketplace %} selected {% endif %}
                                value="{{ marketplace.name }}">{{ marketplace.name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md-2">
            <input type="date" name="date" id="date" class="form-control" {% if request.GET.date %} value="{{ request.GET.date }}" {% endif %}>
        </div>
        <div class="col-md-2">
            <select name="devise" id="devise" class="form-control">
                <option value="">All devise</option>
                <option {% if request.GET.devise == 'EUR' %} selected {% endif %} value="EUR">EUR</option>
                <option {% if request.GET.devise == 'DOL' %} selected {% endif %} value="DOL">DOL</option>
            </select>
        </div>
        <div class="col-md-2">
            <input type="amount" name="amount" id="amount" class="form-control" placeholder="Amount exceeding"
                    {% if request.GET.amount %} value="{{ request.GET.amount }}" {% endif %}>
        </div>
        <input type="submit" value="Search" class="btn btn-primary">
    </form>
</article>

orders/templates/orders/list_orders.html
{% extends 'global.html' %}
{% block title %}List orders{% endblock %}
{% block content %}
    <h1 class="text-center">Orders list</h1>
    <section id="all_orders">
        {% include 'orders/form.html' %}
        <div class="col-md-12">
            {% for order in all_orders %}
                <article class="one_order col-md-6">

                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h2><a style="color: #ffffff;" href="/orders/{{ order.id }}">Order
                                    n° {{ order.order_id }}</a></h2>
                            </div>
                        </div>
                        <div class="panel-body text-center">
                            <div class="market">{{ order.marketplace }}</div>
                            <div class="date">{{ order.payment_date|date:'d/m/Y' }}</div>
                            <div class="amount">{{ order.order_amount }} {{ order.order_currency|lower|title }}</div>
                            <div class="products">
                                {% for product in order.products_set.all %}
                                    <div class="product">
                                        <p>{{ product.quantity }} - {{ product.title }}
                                            ({{ product.price_unit }} {{ order.order_currency }} unit)</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>

{% endblock %}

orders/templates/orders/search.html
{% extends 'global.html' %}
{% block title %}List orders{% endblock %}
{% block content %}
    <h1 class="text-center">Orders list</h1>
    <section id="all_orders">
    {% include 'orders/form.html' %}
        <div class="col-md-12">
            {% for order in all_orders %}
                <article class="one_order col-md-6">

                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h2><a style="color: #ffffff;" href="/orders/{{ order.id }}">Order
                                    n° {{ order.order_id }}</a></h2>
                            </div>
                        </div>
                        <div class="panel-body text-center">
                            <div class="market">{{ order.marketplace }}</div>
                            <div class="date">{{ order.payment_date|date:'d/m/Y' }}</div>
                            <div class="amount">{{ order.order_amount }} {{ order.order_currency|lower|title }}</div>
                            <div class="products">
                                {% for product in order.products_set.all %}
                                    <div class="product">
                                        <p>{{ product.quantity }} - {{ product.title }}
                                            ({{ product.price_unit }} {{ order.order_currency }} unit)</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>

{% endblock %}